### ISSUE TITLE
Do I need a specific Blender, Krita and Addon version?

### ISSUE THREAD

**Issue by hansnolte** [RxLaboratory/DuBLF_Duik#27]
I have tried different Blender (2.8 - 3.0) and Krita (4.2 - 5.0) versions, furthermore I have tried all available Blender Im-/ and Krita Export Addon.
Unfortunately, I always get the same wrong result.
I am on Win 10.
Am grateful for any advice.

![krita](https://user-images.githubusercontent.com/7922627/135080646-cbed86fd-43e8-4cf8-a606-67f4c2392536.jpg)
![blender](https://user-images.githubusercontent.com/7922627/135080666-d20c32d6-c962-4133-8de2-9054250e74a5.jpg)

[Krita-Business-Boy.zip](https://github.com/RxLaboratory/DuBLF_Duik/files/7243638/Krita-Business-Boy.zip)

**Comment by Nico-Duduf** [comment]
Hi,

Sorry for the late reply, we've been very busy.

I assume you're trying to export from Krita / Import to blender using the "OCA" tool we've dvelopped.

This OCA format is not meant for cut-out characters, but for Cel (traditionnal) frame-by-frame animation (Open Cel Animation).
We're workig on another format, OCO (Open Cut-Out) for what you're trying to achieve, but it's not available yet; this work was funded by a crowdfunding campagin, and actually it was **not** funded, we did not collect enough for this milestone, so it's not a priority and we don't know exactly when (and if) it will be available.
